export const projects = [
  {
    title: 'Victor AI ChatBot',
    description: "A modern, responsive AI chatbot powered by Google Gemini and built with Next.js and React. Features include real-time chat, dark/light mode, glassmorphism UI, mobile responsiveness, chat history, one-click copy with popup, and seamless Gemini API integration. Designed for beautiful, intelligent conversations.",
    image: '/images/8.png',
    tags: ['Next.js', 'React', 'Google Gemini AI', 'Tailwind CSS', 'Chatbot'],
    source: 'https://github.com/Shanidhya01/AI-ChatBot',
    visit: 'https://shanidhya-ai-chat-bot.vercel.app/',
    id: 0,
  },
  {
    title: 'Expense Tracker',
    description: "A modern personal finance management platform built with React and Vite. Features include secure user authentication, profile photo upload, responsive expense tracking forms, real-time balance calculations, and intuitive financial categorization. Designed with Tailwind CSS for a clean, mobile-first interface that helps users take control of their personal finances.",
    image: '/images/9.png',
    tags: ['React', 'Vite', 'Tailwind CSS', 'Personal Finance', 'Authentication'],
    source: 'https://github.com/Shanidhya01/expense-tracker',
    visit: 'https://expense-tracker-final-omega.vercel.app/',
    id: 1,
  },
  {
    title: 'Victor AI Assistant',
    description: "An advanced AI voice assistant built with React and Google Gemini AI. Features include voice recognition, text-to-speech with female voice synthesis, cyberpunk-themed UI with animated backgrounds, real-time voice commands, and intelligent conversation capabilities. Victor can open websites, provide information, and engage in natural conversations with users.",
    image: '/images/5.png',
    tags: ['React', 'Google Gemini AI', 'Speech Recognition', 'Voice Synthesis'],
    source : 'https://github.com/Shanidhya01/VOICE-ASSISTANT',
    visit : 'https://voice-assistant-beta-rouge.vercel.app/',
    // visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Entertainment Hub',
    description: "A modern entertainment platform built with React and modern web technologies. Features include movie/TV show discovery, real-time search functionality, detailed content information, user ratings and reviews, and personalized watchlists. Designed with a sleek, responsive interface that provides an immersive entertainment browsing experience across all devices.",
    image: '/images/10.png',
    tags: ['React', 'JavaScript', 'Entertainment', 'Movies', 'API Integration'],
    source: 'https://github.com/Shanidhya01/entertainment-hub',
    visit: 'https://movie-hub-nu-seven.vercel.app/',
    // visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Video Calling WebApp',
    description: "A real-time video calling web application built with Next.js, ZEGOCLOUD, and TypeScript. Features include secure video/audio calls, room creation and joining, responsive design for desktop and mobile, shareable room links, and an intuitive glassmorphism UI. Connect with friends and colleagues seamlessly over the internet with high-quality communication.",
    image: '/images/11.png',
    tags: ['Next.js', 'TypeScript', 'ZEGOCLOUD', 'Tailwind CSS', 'Video Calling'],
    source: 'https://github.com/Shanidhya01/VIDEO-CALLING',
    visit: 'https://video-calling-sk.vercel.app/',
    // visit: 'https://google.com',
    id: 11,
  },
  {
    title: 'Mern Url Shortener',
    description: "A full-stack URL shortener application built with the MERN stack (MongoDB, Express.js, React, Node.js). Features include URL shortening, analytics dashboard for tracking clicks and performance, and a responsive design. Ideal for managing and sharing shortened URLs with ease.",
    image: '/images/12.png',
    tags: ['MongoDB', 'Express.js', 'React', 'Node.js', 'URL Shortener'],
    source: 'https://github.com/Shanidhya01/URL-SHORTENER',
    visit: 'https://url-shortener-frontend-eta-three.vercel.app',
    id: 12,
  },
  {
    title: 'The Solve Space',
    description:  "A modern full-stack web application template built with Next.js, Stackflow, and Appwrite. This project demonstrates seamless navigation and state management using Stackflow, combined with Appwrite's powerful backend-as-a-service features for authentication, database, and storage. Ideal for building scalable, production-ready SaaS apps with a clean developer experience.",
    image: '/images/1.png',
    tags: ['Next.js', 'Stackflow', 'Appwrite', 'TypeScript'],
    source : 'https://github.com/Shanidhya01/StackFlow-Appwrite',
    visit : 'https://github.com/Shanidhya01/StackFlow-Appwrite',
    // visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Quiz App',
    description: "A simple and interactive Quiz App built with HTML, CSS, and JavaScript. Features include multiple-choice questions, instant feedback, score tracking, and a responsive user interface. Designed for learning and testing knowledge in a fun way.",
    image: '/images/6.png', // Update this path to your quiz app image if available
    tags: ['JavaScript', 'HTML', 'CSS', 'Frontend', 'Quiz'],
    source: 'https://github.com/Shanidhya01/Ai-Quiz-Application', // Update with your actual repository URL if available
    visit: 'https://shanidhya-ai-quiz-application-gamma.vercel.app/',      // Update with your live demo link if available
    id: 5,
  },
  {
    title: 'Weather App',
    description: "A responsive Weather App built with HTML, CSS, and JavaScript. Features include real-time weather data fetching, location-based search, dynamic weather icons, and a clean, user-friendly interface. Designed to provide accurate weather updates for any city worldwide.",
    image: '/images/7.png', // Update this path if you have a screenshot
    tags: ['JavaScript', 'HTML', 'CSS', 'Frontend', 'Weather'],
    source: 'https://github.com/Shanidhya01/Weather-app',
    visit: 'https://weather-app-byshanidhya.vercel.app/',
    id: 6,
  },
  {
    title: 'AI Cloudinary SaaS',
    description: "A modern SaaS starter built with Next.js 14, Clerk authentication, Tailwind CSS (with DaisyUI), App Router, and Cloudinary integration for image and video upload, transformation, and sharing. Features include secure authentication, video upload & gallery, social share image generator, and a beautiful, customizable UI.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Shanidhya01/Cloudinary-Saas',
    visit: 'https://github.com/Shanidhya01/Cloudinary-Saas',
    // visit: 'https://google.com',
    id: 7,
  },
  {
    title: 'PassOP Password Manager',
    description: "A simple and modern password manager built with React (Vite), Node.js, Express, and MongoDB. PassOP lets you securely store, view, copy, edit, and delete your passwords for different websites. Features include a responsive UI, toast notifications, and a clean, minimal design.",
    image: '/images/3.jpg',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Vite', 'Tailwind CSS'],
    source: 'https://github.com/Shanidhya01/Password-Manager',
    visit: 'https://github.com/Shanidhya01/Password-Manager',
    id: 8,
  },
  {
    title: '3D Solar System Simulation',
    description: "A fully interactive 3D simulation of the Solar System built with Three.js. Features real-time planetary orbits, individual speed controls, pause/resume, dark/light mode, planet tooltips, and a starfield background. The app is fully responsive and allows users to explore the solar system with an intuitive camera interface.",
    image: '/images/4.jpg',
    tags: ['Three.js', 'JavaScript', '3D', 'Frontend'],
    source: 'https://github.com/Shanidhya01/3-D-Solar-System',
    visit: 'https://3-d-solar-system-topaz.vercel.app/',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2024, text: 'Started my journey', },
  { year: 2024, text: 'Worked on my first project', },
  { year: 2024, text: 'Learned React and built several projects', },
  { year: 2025, text: 'Explored backend technologies and built full-stack applications', },
];